volkamerlab/volkamerlab_org

data/team/team.yaml

Provide Twitter link in my profile

Add Twitter

---

data/team/team.yaml

Changing one-liner for now from : 
_Scalable alchemical free energy calculations and machine learning for drug discovery_
to 
_Machine learning for kinase drug discovery_.

💬 Change one-liner of research description

---

data/team/team.yaml

Add project titles in teams details

Add project titles in team details

---

config.toml

Update HTML renderer config so we can use latest Hugo

Set unsafe = True (needed in Hugo 0.60+)

---

content/_index.md

Add info about our covid project

---

content/publications/_index.md
layouts/partials/publication.html
layouts/section/publications.html

Add autogenerated publications page

---

content/projects/cytotox.md
content/projects/knowtox.md
data/publications/publications.yaml
data/team/members.yaml

I added figure captions including link to the publication (in publications.yaml) and added my github to members.yaml
Two comments on other parts (They are also added as comments now)
* In the cytotoxicity project, the publication is labelled "Webel, 2019" even though the publication came out in 2020, right? I think, this might be a bit confusing...
* In members.yaml, for Jeremie, did you on purpose write "role: Scientist" and not "role: Postdoc"?
The website looks great, thanks for your work, @jaimergp !!

Morgeral knowtox2

---

content/outreach/struc2drug.md

Add upcoming struc2drug seminar details to website.
None

Add next struc2drug seminar details

---

content/blog/next-struc2drug-meeting.md

Oops the blog post

---

.github/workflows/ci.yaml

Try to make tests pass by allowing some known failures.

Exclude some more false negatives 404s

---

data/team/members.yaml

This PR updates team member details for me.

update team members

---

content/blog/kinfraglib-chemrxiv.md

Add blog post to announce KinFragLib preprint on ChemRxiv.
None

Add KinFragLib blog post

---

content/outreach/struc2drug.md

Add upcoming struc2drug seminar
None.

Add upcoming struc2drug seminar

---

content/projects/kissim.md

Kooistra's link was broken. This should be the new one.

Fix ku.dk link in kissim

---

content/projects/kinfraglib.md
data/publications/publications.yaml
layouts/projects/single.html

Add reference to KinFragLib
https://chemrxiv.org/articles/preprint/KinFragLib_Exploring_the_Kinase_Inhibitor_Space_Using_Subpocket-Focused_Fragmentation_and_Recombination/12696392/1

Add kinfraglib preprint

---

content/outreach/struc2drug.md

Add new event and reformat all events.
None

Add upcoming event + reformat all events

---

content/projects/kinfraglib.md
content/projects/kissim.md

https://klifs.vu-compmedchem.nl/  -> https://klifs.net/

Update KLIFS links

---

.gitignore
data/publications/publications.yaml
data/team/members.yaml

This PR adds the new SHP2 publication as well as Mareike and Sakshi to the website.

Shp2 Mareike Sakshi

---

.github/workflows/ci.yaml

The other one is a bit brittle

try with a different link checker

---

content/outreach/struc2drug.md

Add January struc2drug session to website.

Add new struc2drug session

---

content/outreach/struc2drug.md

Add details for struc2drug seminar in March 2021.
None.

Add struc2drug seminar in March

---

content/blog/deep_learning_review.md
data/publications/publications.yaml

Publication updates

---

data/team/members.yaml

Add social media details for Dominique
- LinkedIn
- Google Scholar
- Twitter

DS: Add social media details

---

content/outreach/struc2drug.md

Add struc2drug event for July

---

content/outreach/struc2drug.md

Update struc2drug July event.
None.

Update struc2drug July event

---

data/publications/publications.yaml

Add publications
- ChemBioSim: https://pubmed.ncbi.nlm.nih.gov/34153183/
- TOC chapter: https://pubs.acs.org/doi/abs/10.1021/bk-2021-1387.ch010

Add publications: ChemBioSim and TOC chapter

---

.github/workflows/ci.yaml
content/outreach/struc2drug.md

Clean up struc2drug site.
None

Move last struc2drug event; next event TBA

---

content/outreach/struc2drug.md

Add the details for the struc2drug Nov session.

Add struc2drug Nov session

---

content/education/cadd-seminar.md
content/outreach/struc2drug.md

Update struc2drug website
- Add back struc2drug contact details (Twitter and organizer email address)
- Add past and future organizers with contact details
Also: Fix some broken links.

Add struc2drug contact details + organizers

---

content/blog/teachopencadd-2021-release.md

Add blog post on TOC 2021 release
None

Blog post on our TeachOpenCADD 2021 release

---

content/outreach/struc2drug.md

Move Dec struc2drug event to "past events"; leave template text for "upcoming events" (as comment).

Move struc2drug Dec event to past events

---

content/outreach/struc2drug.md

List new struc2drug organizers first!

List new organizers first!

---

content/research/machine-learning/_index.md

ML research: fix maxsmi link.

---

content/blog/kissim-chemrxiv.md
content/projects/kissim.md

Update KiSSim project + add blog post

Add KiSSim blog post

---

content/blog/opencadd-klifs-joss.md

Add OpenCADD-KLIFS blog post

---

data/publications/publications.yaml
data/team/members.yaml

Update publications and team

---

.github/workflows/ci.yaml

Run CI on Tuesdays instead of nightly runs.

Run CI only Tuesdays

---

data/team/members.yaml

- Add back Talia to the team :)
- Add Dominique's email

Update team page

---

data/team/members.yaml
layouts/partials/contact.html

Update info Andrea

---

data/team/members.yaml
layouts/section/team.html

Add affiliations

---

data/team/members.yaml
layouts/section/team.html

Move @t-kimber  and @dominiquesydow to alumni & add the ability for alumni to link to external websites (e.g. personal website or LinkedIn).

Update DS/TK profiles

---

layouts/section/team.html

Add alumni contact in a new browser window or tab

Add alumni contact in a new browser window or tab

---

content/blog/teachopencadd-dl-edition.md
data/publications/publications.yaml

Add teachOpenCADD-DL paper and blogpost

---

data/team/members.yaml

change the email with FU instead of Charite

update Yonghui's email

---

content/projects/kinfrag-ml.md
content/research/_index.md
content/research/structure-based/kinases.md
data/team/members.yaml

To-Do: 
I added the project under structure-based -> kinase-focused methods. On the research overview page, I grouped it under kinase projects but also mentioned it under machine learning based methods.

Added KinFragML project page

---

data/publications/publications.yaml

Add AI for natural products paper

---

data/publications/publications.yaml

Add Benchmarking cross-docking paper

---

content/projects/kinodata-3D.md
content/projects/protect.md
content/research/_index.md
content/research/machine-learning/_index.md
content/research/structure-based/_index.md
data/publications/publications.yaml
data/team/members.yaml

adding PROTect project info

---

data/publications/publications.yaml

Add guided docking and ECF-T papers

---

data/team/members.yaml

Update Guillermo's status

---

data/publications/publications.yaml
layouts/section/publications.html

#154 This pull request was created to add two sections to the Publications webpage; **Preprint** and **Peer-reviewed Publications**.

Add preprint section to publication page

---

data/team/members.yaml

Update Hamza's Information

---

data/publications/publications.yaml

Add Florian's paper

---

content/positions/_index.md
content/publications/_index.md
content/team/_index.md

Add positions section

---

content/positions/_index.md

Remove unnecessary information

---

content/positions/_index.md

Add master thesis topic

---

content/blog/bachelor_thesis_katharina.md

Adding new blog post about the bachelor thesis of Katharina.

Blog post: Bachelor Thesis Katharina

---

content/blog/reliable_sauron.md

* added blog post on reliable Sauron publication

Blog post "Reliable anti-cancer drug senstivity prediction and prioritization"

---

content/blog/afnan_new.md
content/blog/nlp_in_bio_n_chem_symposium.md
content/blog/tranformers_4mpp_review.md
content/projects/protect.md

adding blog posts for joining the lab, the NLP symposium, and the transformers_4mpp review

updating blog posts for Afnan.

---

content/blog/lisa-new.md
content/positions/_index.md
data/team/members.yaml

Team page: 
Blog:
Working with us section:

added lisa info

---

data/team/members.yaml

project info

---

content/blog/christmas-party.md
content/research/_index.md

Christmas blog post

---

data/publications/publications.yaml

Add Raquel's paper

---

data/team/members.yaml

changed email adress since Lenhof servers will be shut down

---

data/team/members.yaml

update Lisa's email (again) to non-student email

---

data/publications/publications.yaml
data/team/members.yaml

Fix Stefanie's phone number for direct dialing
